<a href="https://colab.research.google.com/github/allanzim/treinamento/blob/master/estatisticas_amostragem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
  %pip install sidetable

  import numpy as np
  import pandas as pd

  import sidetable
  from scipy import stats

  import seaborn as sns
  import matplotlib.pyplot as plt

  import plotly.express as px
  import plotly.graph_objects as go

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [22]:
df = pd.read_csv('/content/Iris.csv')

df[df['Id']==32]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
31  32            5.4           3.4            1.5           0.4  Iris-setosa

In [23]:
df.shape

(150, 6)

In [24]:
amostra_simples = df.sample(30, replace = True)

amostra_simples

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
73    74            6.1           2.8            4.7           1.2   
134  135            6.1           2.6            5.6           1.4   
134  135            6.1           2.6            5.6           1.4   
47    48            4.6           3.2            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
57    58            4.9           2.4            3.3           1.0   
94    95            5.6           2.7            4.2           1.3   
101  102            5.8           2.7            5.1           1.9   
110  111            6.5           3.2            5.1           2.0   
11    12            4.8           3.4            1.6           0.2   
0      1            5.1           3.5            1.4           0.2   
58    59            6.6           2.9            4.6           1.3   
123  124            6.3           2.7            4.9           1.8   
126  127            6.2           2.8            4.8           1.8   
12    13            4.8           3.0            1.4           0.1   
117  118            7.7           3.8            6.7           2.2   
37    38            4.9           3.1            1.5           0.1   
57    58            4.9           2.4            3.3           1.0   
28    29            5.2           3.4            1.4           0.2   
101  102            5.8           2.7            5.1           1.9   
134  135            6.1           2.6            5.6           1.4   
95    96            5.7           3.0            4.2           1.2   
19    20            5.1           3.8            1.5           0.3   
91    92            6.1           3.0            4.6           1.4   
94    95            5.6           2.7            4.2           1.3   
22    23            4.6           3.6            1.0           0.2   
18    19            5.7           3.8            1.7           0.3   
106  107            4.9           2.5            4.5           1.7   
78    79            6.0           2.9            4.5           1.5   
137  138            6.4           3.1            5.5           1.8   

             Species  
73   Iris-versicolor  
134   Iris-virginica  
134   Iris-virginica  
47       Iris-setosa  
9        Iris-setosa  
57   Iris-versicolor  
94   Iris-versicolor  
101   Iris-virginica  
110   Iris-virginica  
11       Iris-setosa  
0        Iris-setosa  
58   Iris-versicolor  
123   Iris-virginica  
126   Iris-virginica  
12       Iris-setosa  
117   Iris-virginica  
37       Iris-setosa  
57   Iris-versicolor  
28       Iris-setosa  
101   Iris-virginica  
134   Iris-virginica  
95   Iris-versicolor  
19       Iris-setosa  
91   Iris-versicolor  
94   Iris-versicolor  
22       Iris-setosa  
18       Iris-setosa  
106   Iris-virginica  
78   Iris-versicolor  
137   Iris-virginica

In [25]:
amostra_simples.shape

(30, 6)

In [26]:
# amostragem sistemática
# criar uma função para pegar uma amostra sistematica
# np.arange(X, len(df) , step = step) - primeiro termo x, tamanho do dataframe, incremento

def amostragem_sistematica(df, step):
  indexes = np.arange(1, len(df) , step = step)
  amostra_sistematica = df.iloc[indexes]
  return amostra_sistematica

amostra_sistematica = amostragem_sistematica(df, 3)

display(amostra_sistematica)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
1      2            4.9           3.0            1.4           0.2   
4      5            5.0           3.6            1.4           0.2   
7      8            5.0           3.4            1.5           0.2   
10    11            5.4           3.7            1.5           0.2   
13    14            4.3           3.0            1.1           0.1   
16    17            5.4           3.9            1.3           0.4   
19    20            5.1           3.8            1.5           0.3   
22    23            4.6           3.6            1.0           0.2   
25    26            5.0           3.0            1.6           0.2   
28    29            5.2           3.4            1.4           0.2   
31    32            5.4           3.4            1.5           0.4   
34    35            4.9           3.1            1.5           0.1   
37    38            4.9           3.1            1.5           0.1   
40    41            5.0           3.5            1.3           0.3   
43    44            5.0           3.5            1.6           0.6   
46    47            5.1           3.8            1.6           0.2   
49    50            5.0           3.3            1.4           0.2   
52    53            6.9           3.1            4.9           1.5   
55    56            5.7           2.8            4.5           1.3   
58    59            6.6           2.9            4.6           1.3   
61    62            5.9           3.0            4.2           1.5   
64    65            5.6           2.9            3.6           1.3   
67    68            5.8           2.7            4.1           1.0   
70    71            5.9           3.2            4.8           1.8   
73    74            6.1           2.8            4.7           1.2   
76    77            6.8           2.8            4.8           1.4   
79    80            5.7           2.6            3.5           1.0   
82    83            5.8           2.7            3.9           1.2   
85    86            6.0           3.4            4.5           1.6   
88    89            5.6           3.0            4.1           1.3   
91    92            6.1           3.0            4.6           1.4   
94    95            5.6           2.7            4.2           1.3   
97    98            6.2           2.9            4.3           1.3   
100  101            6.3           3.3            6.0           2.5   
103  104            6.3           2.9            5.6           1.8   
106  107            4.9           2.5            4.5           1.7   
109  110            7.2           3.6            6.1           2.5   
112  113            6.8           3.0            5.5           2.1   
115  116            6.4           3.2            5.3           2.3   
118  119            7.7           2.6            6.9           2.3   
121  122            5.6           2.8            4.9           2.0   
124  125            6.7           3.3            5.7           2.1   
127  128            6.1           3.0            4.9           1.8   
130  131            7.4           2.8            6.1           1.9   
133  134            6.3           2.8            5.1           1.5   
136  137            6.3           3.4            5.6           2.4   
139  140            6.9           3.1            5.4           2.1   
142  143            5.8           2.7            5.1           1.9   
145  146            6.7           3.0            5.2           2.3   
148  149            6.2           3.4            5.4           2.3   

             Species  
1        Iris-setosa  
4        Iris-setosa  
7        Iris-setosa  
10       Iris-setosa  
13       Iris-setosa  
16       Iris-setosa  
19       Iris-setosa  
22       Iris-setosa  
25       Iris-setosa  
28       Iris-setosa  
31       Iris-setosa  
34       Iris-setosa  
37       Iris-setosa  
40       Iris-setosa  
43       Iris-setosa  
46       Iris-setosa  
49       Iris-setosa  
52   Iris-versicolor 

In [27]:
# amostragem estratificada - selecionar de forma aleatoria 2 elementos de cada subgrupo

df1 = sns.load_dataset('iris')

df1.groupby('species', group_keys=False).apply(lambda x : x.sample(4))



sepal_length  sepal_width  petal_length  petal_width     species
44            5.1          3.8           1.9          0.4      setosa
13            4.3          3.0           1.1          0.1      setosa
5             5.4          3.9           1.7          0.4      setosa
19            5.1          3.8           1.5          0.3      setosa
61            5.9          3.0           4.2          1.5  versicolor
66            5.6          3.0           4.5          1.5  versicolor
57            4.9          2.4           3.3          1.0  versicolor
55            5.7          2.8           4.5          1.3  versicolor
115           6.4          3.2           5.3          2.3   virginica
127           6.1          3.0           4.9          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
140           6.7          3.1           5.6          2.4   virginica

In [28]:
#df.groupby('Species', group_keys=False).apply(lambda x : x.sample(4))


In [29]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [97]:
# amostragem clusterizada - criar cluster aleatórios
df2 = df
def amostra_cluster(df, n_por_cluster, n_cluster):

# n = tamanho do df
  n = len(df)
# k = numero de divisões por clusters - vai pegar o tamanho total do dataframe e dividir pelo número de elementos que queremos por cluster
  k = int(n/n_por_cluster)

# inicia a variavel vazia
  data = None



  for i in range(k):

    # pega n_por_cluster elemento aleatórios do dataframe
    sample_i = df.sample(n_por_cluster)
    # cria uma coluna CLUSTER no dataframe - função repeat(a,b) do numpy repete o termo a, b vezes
    # neste caso, ele vai colocar o indice i em na coluna cluster em todos os elementos aleatórios escolhidos na função anterior
    sample_i['cluster'] = np.repeat(i, len(sample_i))
    
    #df = df.drop(index = sample_i.index)
    # concatena as variáveis data e sample_i
    data = pd.concat([data, sample_i], axis = 0)

  # retorna um array escolhendo números aleatórios entre 0 e k e o tamanho é o número de clusters
  escolha_cluster_aleatorio = np.random.randint(0, k, size = n_cluster)

  # pega os clusters aleatórios selecionados na função anterior
  sample = data[data.cluster.isin(escolha_cluster_aleatorio)]

  return sample



sample = amostra_cluster(df = df, n_por_cluster = 30, n_cluster = 2)

#print('df fora do for: ', df)
sample

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
77    78            6.7           3.0            5.0           1.7   
58    59            6.6           2.9            4.6           1.3   
52    53            6.9           3.1            4.9           1.5   
79    80            5.7           2.6            3.5           1.0   
40    41            5.0           3.5            1.3           0.3   
6      7            4.6           3.4            1.4           0.3   
48    49            5.3           3.7            1.5           0.2   
54    55            6.5           2.8            4.6           1.5   
135  136            7.7           3.0            6.1           2.3   
110  111            6.5           3.2            5.1           2.0   
85    86            6.0           3.4            4.5           1.6   
102  103            7.1           3.0            5.9           2.1   
1      2            4.9           3.0            1.4           0.2   
17    18            5.1           3.5            1.4           0.3   
0      1            5.1           3.5            1.4           0.2   
112  113            6.8           3.0            5.5           2.1   
130  131            7.4           2.8            6.1           1.9   
4      5            5.0           3.6            1.4           0.2   
148  149            6.2           3.4            5.4           2.3   
36    37            5.5           3.5            1.3           0.2   
90    91            5.5           2.6            4.4           1.2   
75    76            6.6           3.0            4.4           1.4   
127  128            6.1           3.0            4.9           1.8   
82    83            5.8           2.7            3.9           1.2   
27    28            5.2           3.5            1.5           0.2   
78    79            6.0           2.9            4.5           1.5   
56    57            6.3           3.3            4.7           1.6   
144  145            6.7           3.3            5.7           2.5   
93    94            5.0           2.3            3.3           1.0   
142  143            5.8           2.7            5.1           1.9   
44    45            5.1           3.8            1.9           0.4   
141  142            6.9           3.1            5.1           2.3   
61    62            5.9           3.0            4.2           1.5   
125  126            7.2           3.2            6.0           1.8   
42    43            4.4           3.2            1.3           0.2   
100  101            6.3           3.3            6.0           2.5   
95    96            5.7           3.0            4.2           1.2   
22    23            4.6           3.6            1.0           0.2   
148  149            6.2           3.4            5.4           2.3   
25    26            5.0           3.0            1.6           0.2   
116  117            6.5           3.0            5.5           1.8   
104  105            6.5           3.0            5.8           2.2   
59    60            5.2           2.7            3.9           1.4   
40    41            5.0           3.5            1.3           0.3   
114  115            5.8           2.8            5.1           2.4   
101  102            5.8           2.7            5.1           1.9   
144  145            6.7           3.3            5.7           2.5   
117  118            7.7           3.8            6.7           2.2   
50    51            7.0           3.2            4.7           1.4   
86    87            6.7           3.1            4.7           1.5   
16    17            5.4           3.9            1.3           0.4   
19    20            5.1           3.8            1.5           0.3   
113  114            5.7           2.5            5.0           2.0   
62    63            6.0           2.2            4.0           1.0   
81    82            5.5           2.4            3.7           1.0   
6      7            4.6           3.4            1.4           0.3   
119  120        

In [98]:
sample.groupby(['cluster'])['cluster'].count()

cluster
0    30
2    30
Name: cluster, dtype: int64

In [31]:
# np.repeat(3, 3)

x = np.array([[1,2],[3,4]])
np.repeat(x, 3)


#array([1, 1, 2, 2, 3, 3, 4, 4])
#np.repeat(x, 3, axis=1)
#array([[1, 1, 1, 2, 2, 2],
#       [3, 3, 3, 4, 4, 4]])
#np.repeat(x, [1, 2], axis=0)
#array([[1, 2],
#       [3, 4],
#       [3, 4]])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])